name: Composer & Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Run test suite
      run: PHPUNIT_USER_ID="${{secrets.PHPUNIT_USER_ID}}" PHPUNIT_COOKIES="${{secrets.PHPUNIT_COOKIES}}" vendor/bin/phpunit --configuration phpunit.xml.dist
